
import streamlit as st
import pandas as pd
import os
import time
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Import agents
from agents.rag_agent import RAGAgent
from agents.sql_agent import SQLAgent
from agents.viz_agent import VizAgent
from agents.synthesis_agent import SynthesisAgent

# Page config
st.set_page_config(
    page_title="ISO Standards AI Assistant",
    page_icon="🔍",
    layout="wide"
)

# Custom CSS for "Pro" Look
st.markdown("""
<style>
    /* Global Font adjustments */
    .stApp {
        font-family: 'Inter', sans-serif;
    }
    
    /* Header styling */
    h1 {
        font-weight: 700 !important;
        background: -webkit-linear-gradient(45deg, #0ea5e9, #6366f1);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        padding-bottom: 1rem;
    }
    
    /* Chat message styling */
    .stChatMessage {
        background-color: transparent !important;
        border: none !important;
    }
    .stChatMessage[data-testid="stChatMessage"]:nth-child(odd) {
        background-color: rgba(255, 255, 255, 0.05) !important;
        border-radius: 10px;
    }
    
    /* Sidebar polish (Dark mode compatible) */
    section[data-testid="stSidebar"] {
        border-right: 1px solid rgba(255, 255, 255, 0.1);
    }
    
    /* Hide Deploy button */
    .stDeployButton {
        display: none;
    }
    
    /* Button styling */
    .stButton button {
        border-radius: 8px;
        transition: all 0.2s ease-in-out;
        border: 1px solid rgba(255, 255, 255, 0.1);
    }
    .stButton button:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.3);
        border-color: #6366f1;
    }
</style>
""", unsafe_allow_html=True)

# Initialize Session State
if "messages" not in st.session_state:
    st.session_state.messages = []

# Helper to get actual standards count
def get_standards_count():
    try:
        import sqlite3
        conn = sqlite3.connect('iso_standards.db')
        cursor = conn.cursor()
        cursor.execute("SELECT count(*) FROM standards")
        count = cursor.fetchone()[0]
        conn.close()
        return count
    except:
        return 0

std_count = get_standards_count()

# Title and header
st.title("ISO Standards Intelligence")

# Check for Demo Data signature (exactly 3000 records as generated by prepare_data.py)
if std_count == 3000:
    st.warning("⚠️ **DEMO MODE ACTIVE**: You are currently exploring a **fictitious** dataset generated for testing purposes. Real ISO standards are not loaded.")

st.markdown(f"""
<div style='margin-bottom: 2rem; font-size: 1.1em; color: #94a3b8;'>
Explore <b>{std_count:,} international standards</b> using AI-powered search.
</div>
""", unsafe_allow_html=True)

# Sidebar settings
with st.sidebar:
    # Fallback to text/emoji if image fails
    st.markdown("### 🏢 ISO Intelligence")
    st.markdown("### Configuration")
    
    # Check for API Key in env
    env_key = os.environ.get("GROQ_API_KEY")
    
    if not env_key:
        api_key = st.text_input("Groq API Key", type="password", help="Enter your key to unlock features")
        if api_key:
            os.environ["GROQ_API_KEY"] = api_key
            st.rerun()
    else:
        st.success("✅ System Online")
    
    st.markdown("---")
    st.markdown("### About")
    st.markdown("""
    **Version:** 2.1.0 Pro  
    **Data:** Official ISO Open Data  
    **Designed and developed by Yves Zango**
    """)

# Initialize Agents
@st.cache_resource
def load_agents():
    return RAGAgent(), SQLAgent(), VizAgent(), SynthesisAgent()

rag, sql_agent, viz, synth = load_agents()

# Check API Key to block main UI if missing
if not os.environ.get("GROQ_API_KEY"):
    st.info("👋 Welcome! Please configure your API Key in the sidebar to proceed.")
    st.stop()

# --- AMORCES (Suggested Questions) ---
# Function to handle button clicks
def handle_click(prompt):
    st.session_state.current_query = prompt

st.markdown("### 💡 Quick Starters")

# Row 1: Topics
col1, col2, col3 = st.columns(3)
with col1:
    st.button("🔐 Cybersecurity (ISO 27001)", 
             on_click=handle_click, 
             args=("What are the ISO standards for cybersecurity?",),
             use_container_width=True)
with col2:
    st.button("🤖 Artificial Intelligence", 
             on_click=handle_click, 
             args=("What are the recent standards on Artificial Intelligence?",),
             use_container_width=True)
with col3:
    st.button("🌍 Environment (ISO 14001)", 
             on_click=handle_click, 
             args=("Explain ISO 14001 standard for environment.",),
             use_container_width=True)
             
# Row 2: Analytics & Insight
st.markdown("###### 📊 Analytics & Trends")
col4, col5, col6 = st.columns(3)
with col4:
    st.button("📈 Top Technical Committees", 
             on_click=handle_click, 
             args=("What are the top 5 most active technical committees?",),
             use_container_width=True)
with col5:
    st.button("📅 Evolution by Year", 
             on_click=handle_click, 
             args=("Show me a chart of published standards evolution by year.",),
             use_container_width=True)
with col6:
    st.button("🔍 Quality Comparison", 
             on_click=handle_click, 
             args=("Compare ISO 9001 version 2015 vs 2008.",),
             use_container_width=True)

# Display Chat History
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        
        # Display artifacts if present
        if "sql_query" in message:
            with st.expander("View SQL Query"):
                st.code(message["sql_query"], language="sql")
        
        if "df_head" in message and message["df_head"] is not None:
            with st.expander("View Data (Excerpt)"):
                st.dataframe(message["df_head"])
                
        if "chart" in message and message["chart"] is not None:
            st.plotly_chart(message["chart"], use_container_width=True)
            
        if "sources" in message and message["sources"]:
            with st.expander("📚 Sources Consulted"):
                for doc in message["sources"]:
                    st.markdown(f"**{doc.get('id', 'N/A')}** - {doc.get('title_en', 'Untitled')}")
                    st.caption(doc.get('abstract', '')[:200] + "...")

# Capture User Input
# Check if a button was clicked (via session state) or chat input usage
user_query = st.chat_input("Ask a question about ISO standards...")
final_query = None

if "current_query" in st.session_state and st.session_state.current_query:
    final_query = st.session_state.current_query
    # Reset immediately so it doesn't trigger again on refresh
    del st.session_state.current_query
elif user_query:
    final_query = user_query

# Process Query
if final_query:
    # 1. Display User Message Immediately
    st.chat_message("user").write(final_query)
    st.session_state.messages.append({"role": "user", "content": final_query})
    
    # 2. Generate Assistant Response
    with st.chat_message("assistant"):
        with st.status("Analyzing...", expanded=True) as status:
            
            # --- AGENT EXECUTION ---
            
            # 1. SQL Agent
            status.write("🔍 Querying database...")
            sql_response = sql_agent.process(final_query)
            
            # 2. RAG Agent
            status.write("📚 Searching texts...")
            rag_response = rag.process(final_query)
            
            # 3. Visualization
            status.write("📊 Generating charts...")
            df_results = None
            chart = None
            viz_type = None
            
            if isinstance(sql_response.get("results"), pd.DataFrame) and not sql_response["results"].empty:
                df_results = sql_response["results"]
                viz_type = viz.determine_chart_type(sql_response["query"], df_results)
                chart = viz.create_chart(df_results, viz_type)
            
            # 4. Synthesis
            status.write("✍️ Drafting response...")
            try:
                final_answer = synth.process(final_query, rag_response, sql_response, viz_type)
            except Exception as e:
                final_answer = f"Error during synthesis: {str(e)}"
            
            status.update(label="Complete", state="complete", expanded=False)
            
        # Display Final Answer
        st.markdown(final_answer)
        
        # Display Chart if available
        if chart:
            st.plotly_chart(chart, use_container_width=True)
            
        # Prepare message payload for history
        msg_payload = {
            "role": "assistant",
            "content": final_answer,
            "sql_query": sql_response.get("query"),
            "df_head": df_results.head(10) if df_results is not None else None,
            "chart": chart,
            "sources": rag_response.get("source_documents", [])
        }
        
        st.session_state.messages.append(msg_payload)
